/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package BuildMe

import java.time.LocalTime
import java.util.concurrent.Executors
import java.util.concurrent.ScheduledExecutorService
import java.util.concurrent.TimeUnit

class App {
    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {
        ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1)
        Runnable task = { println "Time now (ctrl+c to quit): ${LocalTime.now()}" }
        scheduler.scheduleAtFixedRate(task, 0, 10, TimeUnit.SECONDS)
    }
}
